<?php
include __DIR__ . "/../vendor/autoload.php";

use nx\output\status;
use function nx\{container, output, test};

output(['a' => 1, 'b' => 2], 'json');
$r = container('#out.response');
test('json body', $r['body'], ['a' => 1, 'b' => 2]);
test('json code', $r['code'], 200);
test('json format', $r['format'] === 'json', true);
output('not found', 404);
$r = container('#out.response');
test('404 code', $r['code'], 404);
test('404 format null', $r['format'], null);
output(status::NotFound);
$r = container('#out.response');
test('Status enum code', $r['code'], 404);
test('Status enum body null', $r['body'], null);
output('download', 'file', '/tmp/test.txt');
$r = container('#out.response');
test('file format', $r['format'] === 'file', true);
test('file path', $r['file'] === '/tmp/test.txt', true);
$result = null;
container('#out.emit', function($r) use (&$result){ $result = $r; });
output(['name' => 'test'], 'json');
output();
test('pipeline json body', $result['body'], json_encode(['name' => 'test']));
test('pipeline Content-Type', $result['headers']['Content-Type'] ?? '', 'application/json; charset=UTF-8');
output(null, 204);
container('#out.render', null);
output();
test('pipeline 204 body', $result['body'], null);
output('err', 500);
container('#out.render', null);
output();
test('pipeline 500 body', $result['body'], json_encode('err'));
test('pipeline 500 code', $result['code'], 500);
container('#out.format.html', fn(array $r): array => [...$r, 'body' => "<html><body>{$r['body']}</body></html>"]);
output('hi', 'html');
container('#out.render', null);
output();
test('pipeline custom format', $result['body'], '<html><body>hi</body></html>');
container('#out.emit', null);
test();
